version: "3"
services:
  back:
    build:
      context: ./
    volumes:
      - /proyectoDistribuidos/backend/src:/app
    links:
      - db
    ports:
      - "5000:5000"

  front:
    build:
      context: ./
    volumes:
      - /proyectoDistribuidos/frontend:/var/www/html/
    links:
      - back
    ports:
      - "8000:80"

  db:
    image: mysql:5.7
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dombpala_YUGIOHGX99
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
